// Array of video file paths
const videoPaths = [
  `Abbey Rain - Don’t Tell My Manager!.mp4`,
  `Abigaiil Morris Reality Kings .mp4`,
  `Abigail Mac, A Domestic Dicking.mp4`,
  `Adria Rae - Daddy’s Debt.mp4`,
  `Aidra Fox, Unexpected Dinner Guest.mp4`,
  `Alanah Rae - Ten Dollar Whore.mp4`,
  `Aletta Ocean - Lost In ZZ.mp4`,
  `Alexis Fawx - Let Mommy Help You.mp4`,
  `Alison Tyer, Get The Picture_.mp4`,
  `Alli Rae, Brandi Love, Kimmy Granger - The Wild Card.mp4`,
  `Alyce Anderson - Stepdads Side Of The Bed .mp4`,
  `Angelina Elizabeth.ts`,
  `Annabel Redd - Annabel Redd On Video.mp4`,
  `Antonella Lasirena - Pierced Nipple Girl Gets Fucked Hard.mp4`,
  `Anya Olsen - Don’t do this to me stepdad.mp4`,
  `Athletic Girl Takes Cock - Dani Daniels.ts`,
  `Ava Addams - Unfaithful Wife Punished.mp4`,
  `Ava Addams, Daisy Summers - Step Daughter And Step Mom.mp4`,
  `Bailey Brooke - My Sister’s Hot Friend.mp4`,
  `Battle For Big Breast Dominance - Angela White - EPORNER.mp4`,
  `Beutifull Arab Lesbain Has Sex - Jon Jon.ts`,
  `Big Ass Facesitting.ts`,
  `Brazzers Presents 1 800 Phone Sex - the Package.ts`,
  `Bunny Colby - The Cuckold And His Wife.mp4`,
  `Carmela Clutch - Take Over The Car Accident.mp4`,
  `Carmen De Luz - Spying on my maid.mp4`,
  `Cassidy Klein, Chanel Preston, The Wettest Dream.mp4`,
  `Cassidy Klein, Veronica Vain - The Day For Giving Thanks.mp4`,
  `Cherie Deville, Dakota Skye, Quality Time.mp4`,
  `Close-up sex ~ Domestic affair soaked in the rain and drowning in`,
  `lust with her father-in-law ~ Rei Kimura.mp4`,
  `Coco Nailed (1080).mp4`,
  `Cum In Me, Not On My Couch.mp4`,
  `Cytherea, Blind Experiment.mp4`,
  `Daisy Diva Gets Pool Tabled By Tyrone Love.mp4`,
  `Dee Williams - Foster Mom Demands Insemination.mp4`,
  `Dylan Phoenix Molly Jane, Big Tits On The Bottom Bunk.mp4`,
  `Ella huges Shy Redheads Want Anal.mp4`,
  `Ella Hughes, Sensual Jane - Lost In ZZ Episode 1.mp4`,
  `EPORNER.COM - [1xFj1VpxOQx] Aranic firi womens sex (360).mp4`,
  `EPORNER.COM - [3bKPNxHQBVH] Nagi Hikaru Jcup Older Sister With`,
  `Divine Breasts Who Is Made Into A Lewd Maid [Decensored] (1080).mp4`,
  `EPORNER.COM - [A0OhyeaFuR1] 9hab arabe sex amateur (480).mp4`,
  `EPORNER.COM - [AUHMeLrp4NZ] Beautiful Mother And Daughter,`,
  `Itadakimas.I Came To See The Woman And Her Daughter Who Had Been`,
  `Conceived Several Decades Ago (1080).mp4`,
  `EPORNER.COM - [f4bFMIOpFZO] Rion Izumi Gets Pounded Like A Bitch In`,
  `Front Of Her Daughter (RM) (720) (720).mp4`,
  `EPORNER.COM - [gFtdpLDXnNd] Dirty With Father In Law, American`,
  `Wife's Body Lovejoy - Megu Fujiura (480).mp4`,
  `EPORNER.COM - [GWlvSquQnnO] ragab mohamedy (240).mp4`,
  `EPORNER.COM - [h8ShcXB7VoV] Japanese Wife Fucked All Day In Front Of`,
  `Her Husband_ (720).mp4`,
  `EPORNER.COM - [j8BO04lY5nH]     arab egypt (240).mp4`,
  `EPORNER.COM - [Jbe9ogyqLxf] STARS-947 A Beautiful Wife Who Runs A`,
  `Vacation Rental I (1080).mp4`,
  `EPORNER.COM - [knyDmsnZHXU] In Egyptian Brothel (360).mp4`,
  `EPORNER.COM - [L6up8MEg1aM] arabic sex (240).mp4`,
  `EPORNER.COM - [p5XKADleMn3] My Younger Brother's Wife My Younger`,
  `Brother's Wife Who Can't Refuse Sex (Misuzu Takeuchi) (720).mp4`,
  `EPORNER.COM - [VGLk7uyuS0W] Celebration! ! Commemorative Work That`,
  `Breaks Through 50 Ripe Comics! ! Up And Coming Mature Woman`,
  `Humiliation! ! Original  Koshiyama Weakness Married Nampa Ntr Hot`,
  `Spring (1080).mp4`,
  `EPORNER.COM - [Vj4FSdbu6cM] Rasha and Rajab and the best nick`,
  `(360).mp4`,
  `EPORNER.COM - [yLtubyspaRu] hot caretaker that takes ups a coach`,
  `after her duty (1080).mp4`,
  `EPORNER.COM - [zrJmYbCk1ZA] Busty Japanese Secretary (1080).mp4`,
  `Esperanza Gomez - I Take Out My Cock In Stepmom's Car.mp4`,
  `Eva Notty, Gia Paige, Prom Pussy.mp4`,
  `filenames.txt`,
  `Full Video - Big Ass Stepsis Abella Danger Lets Her Voyeur Stepbro`,
  `Have it.ts`,
  `Full Video - Hotwife Karla Kush Gets Shared With a Big Cock.ts`,
  `Full Video - Karlee Grey is Stacked but Tyler Doesn't Believe`,
  `They're Real!.ts`,
  `Full Video - NEW SENSATIONS - 'I Can't Resist My Stepsis Big Natural`,
  `Tits' (Autumn Falls).ts`,
  `Full Video - 🔥Daughter Swap - Big Titted Graduating Sluts Swapping`,
  `And Swallowing Their Step Fathers Jizz.ts`,
  `Gabbie Carter - Desirable Brunette Gets Licked And Penetrated.mp4`,
  `Gabbie Carter - Sexy Blonde Fucked By The Big Black Cock.mp4`,
  `Gabbie Carter, LaSirena69 - Lucky Guy.mp4`,
  `Gabbie Carter, LaSirena69 - Perfect Wife.mp4`,
  `Gabriela Lopez - Lopez Family Vacation.mp4`,
  `Gia Paige - I’m Not Leaving!.mp4`,
  `Holly Hendrix, Mandy Muse - My Girlfriend’s Phat Ass Roommate.mp4`,
  `Isabella De Santos - Hot Anal Latina.mp4`,
  `Jayden Jaymes - Big Twits in Uniform- He Comes to America!.mp4`,
  `Jayden Jaymes - I Won’t Tell The Boss.mp4`,
  `JJ cumshot compilation (1080).mp4`,
  `Julianna Vega, Mia Khalifa - Stepmom and Step-daughter.mp4`,
  `Jynx Maze - Jynx’s Juicy Pussy.mp4`,
  `Keisha Grey - Don’t Touch Her 2.mp4`,
  `Keisha Grey - Trying to get her professor’s attention.mp4`,
  `Keisha Grey, Leah Gotti - Best Friends Share Everything.mp4`,
  `Keisha Grey, Mandy Muse - Step-Sister’s Play Tug of War With`,
  `Boyfriend.mp4`,
  `Kelsi Monroe - Banging That Hot Pussy.mp4`,
  `Kelsi Monroe - Kelsi Meets Mandingo.mp4`,
  `Kendra Lust - Big Tit MILF Star Kendra Lust Has A BBC Celebration`,
  `With Dredd.mp4`,
  `Kianna Dior - Your MILF is the Best.mp4`,
  `Kimmy Granger - Don’t Forget To Fuck!.mp4`,
  `Kimmy Granger, Adriana Chechik - class for a hands-on demonstration`,
  `.mp4`,
  `Kristina Rose Anal.ts`,
  `Lauren Phillips - Busty Redhead MILF At Prison.mp4`,
  `Leah Gotti, TUSHY first Anal for Brunette.ts`,
  `Lena Paul - Hot Stepmom.mp4`,
  `Lena Paul - Longtime Best Friend.mp4`,
  `Lennox Luxe Blacked.mp4`,
  `Lilly Ford - Father’s Day Movie Night Surprise.mp4`,
  `Mandy Flores - Flirty Sister Learns A Lesson.mp4`,
  `Mandy Muse - Mandy’s Anal Amusement.mp4`,
  `Manuzinha Black.ts`,
  `Mckenna Rae.ts`,
  `Mea Melone - Lost In ZZ Episode 4.mp4`,
  `Melissa May Romi Rain, Room, Board and Bang.mp4`,
  `Merry Christmas By Honey Tsunama.ts`,
  `Mia Evans, Missy Luv - Snowballing Stepsister Secrets.mp4`,
  `Mia Malkova - My Own Private Tryout.mp4`,
  `Mia Malkova, Natalia Starr - Let’s Have a Threesome.mp4`,
  `Molly Jane - You’re married.mp4`,
  `Monica Has To Spread Her Cheeks So He Can Find Her Anus - Monica`,
  `Santhiago.ts`,
  `Mother Claus Fuck The Grinch.ts`,
  `Natasha Nice - Wealthy Widow.mp4`,
  `Nicole Aniston, The Perfect Maid 2.mp4`,
  `Nika Venom - Curvy Babe Needs Creampie.mp4`,
  `Nina North - The Make Up Exam.mp4`,
  `Our New Maid- Part One.mp4`,
  `Personal Trainers- Session 3.mp4`,
  `Peta Jensen - Big Boob Secretary Does Her Black Boss.mp4`,
  `Porn Habits.mp4`,
  `Preppy Girl Threesome Get Three BBCs BLACKED.ts`,
  `printit.txt`,
  `Rasha And Rajab Quality Up.mp4`,
  `Riley Nixon - Cant Get Enough.mp4`,
  `Riley Reid, Eva Lovia - Sluts In Stockings.mp4`,
  `Riley Takes Monster Dick In Her Ass.mp4`,
  `Romi Rain - Romi Rains In A BBC.mp4`,
  `Rose D. Kush - Rose Kush.ts`,
  `Rose Monroe - Staycation Sex Blues.mp4`,
  `Ryan Smiles, The Replacement.mp4`,
  `Samantha Saint, The Perfect Maid 3.mp4`,
  `Sara Jay - Bring Me The Manager.mp4`,
  `Scarlet Red - Back for 2 Big Black Dicks.mp4`,
  `Sheena Ryder - Sheena In Stepmom Fucks Her Two Sons.mp4`,
  `Sienna West - Sexy Teacher.mp4`,
  `Siri Dahl - Sweet Dinner For My Stepson.mp4`,
  `Skylar Vox, LaSirena69 - It Was The Fucking Realtor.mp4`,
  `Sone385 Uncensored Boobs Ass (1080).mp4`,
  `SPREAD THE LUV the best of Jason Luv BLACKED.ts`,
  `Squad Goals BLACKED.ts`,
  `Stay Away From My Daughter.mp4`,
  `stepMomsTeachSex - Stepmom & Stepson Share Bed & Fuck S7_E3.mp4`,
  `Sunny Lane, The Masturbating Teacher.mp4`,
  `Sybil Stallone - Stepmom’s Spring Cleaning.mp4`,
  `Synnful Latina Does Anal Army Training - Sophia Castello.ts`,
  `The Break-Up.mp4`,
  `The Cuckold Compilation BLACKED.mp4`,
  `Top Blonde Compilation BLACKED GOLDEN.ts`,
  `Valentina Nappi - I’m Horny - Call an Ambulance!.mp4`,
  `Virgo Peridot - Fucking Virgo Peridot in the ass!.mp4`,
  `Watch BLACKED Iconic Gabbie Compilation - Anal, Blonde, Blowjob Porn`,
  `Watch Lesbian Analingus - Milf, Blonde, Big Ass Porn - SpankBang.mp4`,
];

// Dynamically create video gallery
const videoGallery = document.getElementById("videoGallery");

// Loop through the videoPaths array and generate video elements
videoPaths.forEach((videoPath) => {
  // Create a wrapper div for each video
  const videoWrapper = document.createElement("div");
  videoWrapper.classList.add("video-wrapper");

  // Create a video element
  const videoElement = document.createElement("video");
  videoElement.src = "../Porn/" + videoPath;
  videoElement.controls = true;
  videoElement.setAttribute("preload", "metadata");

  // Create a Para element
  const ParaElement = document.createElement("p");
  ParaElement.innerText = videoPath;
  ParaElement.classList.add("ParaElement");

  // Append the video element to the wrapper
  videoWrapper.appendChild(videoElement);

  // Append the Para element to the wrapper
  videoWrapper.appendChild(ParaElement);

  // Append the wrapper to the gallery
  videoGallery.appendChild(videoWrapper);
});
